import type { InsertExercise } from "@shared/schema";

export const seedExercises: InsertExercise[] = [
  {
    name: "Goblet Squat",
    description: "Hold weight at chest level and perform a deep squat",
    movementPattern: "squat",
    equipment: ["dumbbells", "kettlebell"],
    difficulty: "beginner",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core", "hamstrings"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Keep chest up", "Drive through heels", "Knees track over toes"],
  },
  {
    name: "Romanian Deadlift",
    description: "Hip hinge movement emphasizing hamstrings and glutes",
    movementPattern: "hinge",
    equipment: ["barbell", "dumbbells", "kettlebell"],
    difficulty: "intermediate",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower back", "core"],
    isFunctional: 1,
    isCorrective: 0,
    formTips: ["Maintain neutral spine", "Push hips back", "Feel stretch in hamstrings"],
  },
  {
    name: "Push-up",
    description: "Classic bodyweight push exercise",
    movementPattern: "push",
    equipment: ["bodyweight"],
    difficulty: "beginner",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["shoulders", "core"],
    isFunctional: 1,
    isCorrective: 0,
    formTips: ["Maintain plank position", "Lower chest to floor", "Push explosively"],
  },
  {
    name: "Pull-up",
    description: "Vertical pull bodyweight exercise",
    movementPattern: "pull",
    equipment: ["pullupbar"],
    difficulty: "intermediate",
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["upper back", "core"],
    isFunctional: 1,
    isCorrective: 0,
    formTips: ["Full range of motion", "Pull chest to bar", "Control descent"],
  },
  {
    name: "Farmer's Carry",
    description: "Walk while holding heavy weights at sides",
    movementPattern: "carry",
    equipment: ["dumbbells", "kettlebell"],
    difficulty: "beginner",
    primaryMuscles: ["traps", "forearms"],
    secondaryMuscles: ["core", "shoulders"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Stand tall", "Engage core", "Take controlled steps"],
  },
  {
    name: "Turkish Get-up",
    description: "Complex movement from lying to standing with weight overhead",
    movementPattern: "rotation",
    equipment: ["kettlebell", "dumbbells"],
    difficulty: "advanced",
    primaryMuscles: ["shoulders", "core"],
    secondaryMuscles: ["full body"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Move slowly", "Keep eyes on weight", "Maintain stability throughout"],
  },
  {
    name: "Banded Pull Apart",
    description: "Pull resistance band apart at chest level",
    movementPattern: "pull",
    equipment: ["bands"],
    difficulty: "beginner",
    primaryMuscles: ["rear delts", "upper back"],
    secondaryMuscles: ["rotator cuff"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Keep shoulders down", "Squeeze shoulder blades", "Control the band"],
  },
  {
    name: "Box Step-up",
    description: "Step onto elevated surface with one leg",
    movementPattern: "squat",
    equipment: ["bodyweight", "dumbbells"],
    difficulty: "beginner",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Drive through front heel", "Maintain upright posture", "Control descent"],
  },
  {
    name: "Landmine Press",
    description: "Press barbell from chest in standing position",
    movementPattern: "push",
    equipment: ["barbell"],
    difficulty: "intermediate",
    primaryMuscles: ["shoulders", "chest"],
    secondaryMuscles: ["core", "triceps"],
    isFunctional: 1,
    isCorrective: 0,
    formTips: ["Engage core", "Press in arc motion", "Don't lean back"],
  },
  {
    name: "Kettlebell Swing",
    description: "Explosive hip hinge with kettlebell",
    movementPattern: "hinge",
    equipment: ["kettlebell"],
    difficulty: "intermediate",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["core", "shoulders"],
    isFunctional: 1,
    isCorrective: 0,
    formTips: ["Power from hips", "Snap hips forward", "Arms are guide only"],
  },
  {
    name: "Single-Leg Deadlift",
    description: "Hip hinge on one leg for balance and stability",
    movementPattern: "hinge",
    equipment: ["bodyweight", "dumbbells", "kettlebell"],
    difficulty: "intermediate",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["core", "balance"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Maintain neutral spine", "Balance on one leg", "Reach weight to floor"],
  },
  {
    name: "Plank",
    description: "Static hold in push-up position",
    movementPattern: "core",
    equipment: ["bodyweight"],
    difficulty: "beginner",
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "glutes"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Maintain straight line", "Engage core and glutes", "Breathe steadily"],
  },
  {
    name: "Cable Wood Chop",
    description: "Rotational movement pulling cable across body",
    movementPattern: "rotation",
    equipment: ["cable"],
    difficulty: "intermediate",
    primaryMuscles: ["obliques", "core"],
    secondaryMuscles: ["shoulders"],
    isFunctional: 1,
    isCorrective: 0,
    formTips: ["Rotate from torso", "Keep arms extended", "Control the weight"],
  },
  {
    name: "Overhead Press",
    description: "Press weight from shoulders to overhead",
    movementPattern: "push",
    equipment: ["barbell", "dumbbells"],
    difficulty: "intermediate",
    primaryMuscles: ["shoulders", "triceps"],
    secondaryMuscles: ["core", "upper back"],
    isFunctional: 1,
    isCorrective: 0,
    formTips: ["Engage core", "Press straight up", "Don't lean back"],
  },
  {
    name: "Inverted Row",
    description: "Horizontal pull using bodyweight under bar",
    movementPattern: "pull",
    equipment: ["rack", "pullupbar"],
    difficulty: "beginner",
    primaryMuscles: ["upper back", "biceps"],
    secondaryMuscles: ["rear delts", "core"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Keep body straight", "Pull chest to bar", "Control descent"],
  },
  {
    name: "Suitcase Carry",
    description: "Walk while holding weight on one side",
    movementPattern: "carry",
    equipment: ["dumbbells", "kettlebell"],
    difficulty: "intermediate",
    primaryMuscles: ["obliques", "forearms"],
    secondaryMuscles: ["core", "traps"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Stand tall", "Resist lateral bend", "Walk controlled"],
  },
  {
    name: "Wall Slide",
    description: "Slide arms up wall while maintaining contact",
    movementPattern: "corrective",
    equipment: ["bodyweight"],
    difficulty: "beginner",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["upper back", "rotator cuff"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Maintain wall contact", "Move slowly", "Feel shoulder blade movement"],
  },
  {
    name: "Medicine Ball Slam",
    description: "Explosively slam ball to ground",
    movementPattern: "power",
    equipment: ["medicineball"],
    difficulty: "intermediate",
    primaryMuscles: ["core", "lats"],
    secondaryMuscles: ["shoulders", "full body"],
    isFunctional: 1,
    isCorrective: 0,
    formTips: ["Use full body", "Slam with power", "Brace core on catch"],
  },
  {
    name: "Bulgarian Split Squat",
    description: "Single-leg squat with rear foot elevated",
    movementPattern: "squat",
    equipment: ["bodyweight", "dumbbells"],
    difficulty: "intermediate",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    isFunctional: 1,
    isCorrective: 1,
    formTips: ["Front knee tracks over toe", "Maintain upright torso", "Control descent"],
  },
  {
    name: "Bench Press",
    description: "Press weight from chest while lying on bench",
    movementPattern: "push",
    equipment: ["barbell", "dumbbells"],
    difficulty: "intermediate",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["shoulders"],
    isFunctional: 0,
    isCorrective: 0,
    formTips: ["Retract shoulder blades", "Lower to chest", "Press explosively"],
  },
];
